# Generated by Django 5.1.5 on 2025-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaukt_post_image.png', upload_to=''),
        ),
    ]
