# Generated by Django 5.1.6 on 2025-02-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_author_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post_author',
            name='post',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Post_author',
        ),
    ]
