# Generated by Django 5.1.6 on 2025-04-22 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_author_author_remove_post_author_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='posts.post')),
            ],
        ),
    ]
